config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts

  namespace :admin do
  	resources :articles
  end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
	before_action :find_article, only: %i[show edit update]
	def index
		@articles = Article.all
	end

	def show
	
	end	

	def new

	end	

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to admin_article_path(@article)
		else
			render 'new'		
		end	

	end 
	def edit

	end	
	def update
		if @article.update(article_params)
			redirect_to admin_article_path(@article)
		else
			render 'edit'
		end	
	end

	def destroy
		
	end

	private
	def find_article
      @article = Article.find(params[:id])
    end

	def article_params
		params.require(:article).permit(:title, :body)		
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	def new
		
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end			
	end

	def edit
		@post = Post.find(params[:id])	
    end

    def update
  		@post = Post.find(params[:id])
  		if @post.update(post_params)
  			redirect_to @post
  		else
  			render 'edit'
  		end		
    end

    def destroy
    	@post = Post.find(params[:id])
    	@post.destroy
    	redirect_to posts_path, :notice => "Your post has been deleted successfully."
    end
    	
	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/articles/edit.html.erb
<div class="container">
	<%= form_for [:admin, @article] do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit  class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/admin/articles/index.html.erb
<h1>All articels</h1>
<% @articles.each do |article| %>
	<%= link_to  article.title, admin_article_path(article) %>
<% end %>

app/views/admin/articles/new.html.erb
<h2>New articel</h2>
<div class="container">
	<%= form_for :article, url: admin_articles_path do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit  class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/admin/articles/show.html.erb
<p>Article</p>
<%= @article.title %><br>
<%= @article.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="text-center">Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>
<button class="btn btn-primary">See more..</button>

app/views/posts/edit.html.erb
<div class="container">
	<%= form_for @post do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit  class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
	<h5><%= post.title %></h5>
	<p><%= post.body%></p>
	<%= link_to "Read more", post_path(post), class: "btn btn-primary" %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
	<%= form_for :post, url: posts_path do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit  class: 'btn btn-success' %>
		</div>
	<% end %>
</div>

app/views/posts/show.html.erb
<p><%= @post.title %></p>
<p><%= @post.body %></p>
<p><%= @post.created_at %></p>
<%= link_to 'Delete post', @post, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>